### ISSUE TITLE
Make main.cpp compile succesfully

### ISSUE THREAD

**Issue by shreya1010svg** [shreya1010svg/cafe#1]
On executing main.cpp it is seen that there is an error that says:

> main.cpp:234:6: error: ‘Customer’ was not declared in this scope
      Customer c;
      ^
main.cpp:235:6: error: ‘c’ was not declared in this scope
      c.getRating();
      ^
main.cpp:240:6: error: ‘Customer’ was not declared in this scope
      Customer c;
      ^
main.cpp:241:6: error: ‘c’ was not declared in this scope
      c.displayRating();
      ^

Make the program compile successfully and add necessary documentation to say how this addition makes sense in the project

**Comment by anushka-gupta-31** [comment]
Hey! I would like to work on this.

**Comment by anushka-gupta-31** [comment]
Please check out the changes I have made in my pull request #7
