### ISSUE TITLE
Add item as user input

### ISSUE THREAD

**Issue by shreya1010svg** [shreya1010svg/cafe#5]
> Item item1(1,20,"a",1,"b",2,"",0,"",0,"",0);
					Item item2(2,50,"c",0.5,"a",1,"",0,"",0,"",0);
					int choice;
					cout<<"Do you want to buy item 1 or item 2?";
					cin>>choice;
					if(choice==1)
					{
						item1.personBoughtItem();
						item1.ingridientsForNextWeek();
					}
					else if(choice==2)
					{
						item2.personBoughtItem();
						item2.ingridientsForNextWeek();

This is a code snippet that shows that the items are being hard-coded into the program. Accept it as user input. There should be no change made to the existing methods and general framework of code.

**Comment by dhanushya1** [comment]
Hello, I would like to work on this!
